inventory/api/urls.py
from django.urls import path

from .views import inventories_view

app_name = 'inventory'

urlpatterns = [
    path('inventory/', inventories_view, name='inventory_list'),
]

inventory/urls.py
from django.urls import path

from .views import inventory_list, inventory_detail

app_name = 'inventory'

urlpatterns = [
    path('inventory/', inventory_list, name='inventory_list'),
    path('inventory/<pk>/', inventory_detail, name='inventory_detail'),
]

inventory_management/urls.py
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.views.generic.base import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(url='/inventory/'), name="home"),
    path('admin/', admin.site.urls),
    path("", include("inventory.urls", namespace='inventory')),
    path("api/", include("inventory.api.urls", namespace='inventory_api')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
]

inventory/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Inventory(models.Model):
    name = models.CharField(_('Name'), max_length=56, unique=True)
    description = models.CharField(_("Description"), max_length=256)
    note = models.TextField(_("Note"))
    stock = models.PositiveIntegerField(_("Stock"))
    availability = models.BooleanField(_("Availiability"), default=True)
    supplier = models.ForeignKey('Supplier', related_name='inventories', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("inventory")
        verbose_name_plural = _("inventorys")

    def __str__(self):
        return f'{self.name}: {self.stock}'


class Supplier(models.Model):
    name = models.CharField(_('Supplier Name'), max_length=56)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("supplier")
        verbose_name_plural = _("suppliers")

    def __str__(self):
        return self.name

inventory/api/views.py
from rest_framework.generics import ListAPIView
from django_filters import rest_framework as filters
from rest_framework import filters as rest_filters
from ..models import Inventory
from .filters import InventoryFilter
from .serializers import InventorySerializer


class InventoryListApiView(ListAPIView):
    filter_backends = (filters.DjangoFilterBackend, rest_filters.OrderingFilter)
    filterset_class = InventoryFilter
    ordering_fields = ['name', 'stock', 'created_at']
    queryset = Inventory.objects.select_related('supplier')
    serializer_class = InventorySerializer


inventories_view = InventoryListApiView.as_view()

inventory/views.py
import requests
from requests.exceptions import ConnectionError
from django.http import HttpResponse
from django.shortcuts import reverse, render
from django.views.generic import DetailView

from .models import Inventory


def inventory_list(request):
    template_name = 'inventory/inventories.html'
    url = request.build_absolute_uri(reverse('inventory_api:inventory_list'))
    msg = 'Inventory fetching api is not working properly. Try again later.'
    try:
        response = requests.get(url)
    except ConnectionError:
        return HttpResponse(msg, status_code=503)
    else:
        if response.status_code == 200:
            return render(request, template_name, {'object_list': response.json()})
        else:
            return HttpResponse(msg, status=503)


class InventoryDetailView(DetailView):
    template_name = 'inventory/detail.html'

    def get_queryset(self):
        return Inventory.objects.select_related('supplier')


inventory_detail = InventoryDetailView.as_view()

inventory/templates/inventory/detail.html
{% extends "__base.html" %}
{% load static %}

{% block title %}{{ object.name }} | Inventory Detail{% endblock title %}

{% block contnet %}
<div class="py-4">
  <h4>Inventory Datail</h4>
  <small class="text-muted">Showing Inventory Detail</small>
</div>
<div class="row">
  <div class="col-9">
    <div class="table-responsive">
      <table class="table table-success table-striped">
         <tbody>
          <tr>
            <td>Name:</td>
            <td>Name: {{ object.name }}</td>
          </tr>
          <tr>
            <td>Supplier Name:</td>
            <td>{{ object.supplier.name }}</td>
          </tr>
          <tr>
            <td>Description: </td>
            <td>{{ object.description }}</td>
          </tr>
          <tr>
            <td>Stock: </td>
            <td>{{ object.stock }}</td>
          </tr>
          <tr>
            <td>Availability: </td>
            <td>{{ object.availability }}</td>
          </tr>
          <tr>
            <td>Note: </td>
            <td>{{ object.note }}</td>
          </tr>
          <tr>
            <td>Created Date: </td>
            <td>{{ object.created_at|date }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-3">
    <img src="{% static 'thumbs/inventory_thumbnail.jpg' %}" class="img-thumbnail align-right" alt="Placeholder Image">
  </div>
</div>
{% endblock contnet %}

inventory/templates/inventory/inventories.html
{% extends "__base.html" %}

{% block title %}Inventory List{% endblock title %}

{% block contnet %}
<div class="py-4">
  <h4>Inventories</h4>
  <small class="text-muted">Listing the Inventory</small>
</div>
<div class="table-responsive">
  <table class="table table-success table-striped">
    <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Supplier Name</th>
          <th scope="col">Availibility</th>
        </tr>
      </thead>
       <tbody>
        {% for object in object_list %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td><a href="{% url 'inventory:inventory_detail' object.id %}">{{ object.name }}</a></td>
          <td>{{ object.supplier_name }}</td>
          <td>{{ object.availability }}</td>
        </tr>
        {% empty %}
        <tr>
            <th colspan="4" class="text-center">No inventery has been added yet.</th>
        </tr>
        {% endfor %}
      </tbody>
  </table>
</div>

{% endblock contnet %}

templates/__base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
    <meta name="title" content="Inventory Management System">
    <meta name="description" content="Simple django project to manage inventory system.">
    <meta name="keywords" content="Inventory, Management, Management System, Inventory System">
    <title>{% block title %}Home | Inventory Management System{% endblock %}</title>

    <!-- Current Page Styles -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    {% block head %}

    {% endblock %}
</head>
<body>
<div id="container">
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Inventory Management System</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>
    <div class="container">
      {% block contnet %}

      {% endblock %}
    </div>
</div>

</body>
</html>